### ISSUE TITLE
How to get the BCE Loss?

### ISSUE THREAD

**Issue by XiongFenghhh** [NeuralCarver/Michelangelo#10]
Thank you for your great work!

When training decoder, you used BCE Loss. But how could we get the ground truth occupancy of the query point?

**Comment by Maikouuu** [comment]
Thank you for your interest.

We utilize the ```SDF``` function in the ```pysdf``` library to compute the SDF of each point.

**Comment by XiongFenghhh** [comment]
> Thank you for your interest.
> 
> We utilize the `SDF` function in the `pysdf` library to compute the SDF of each point.

Hello,  I tried to reproduce training procedure recently, but didn't get a good result.  Could you give me some advice?

1.  How many points should be set for the encoder's input point cloud during training?
2. What is the sampling strategy for the query points during training? Is it sampling within an NxNxN volume and near the mesh surface? If volume sampling is used, what is a suitable value for N?

Thanks!

**Comment by Maikouuu** [comment]
Hi, 

1. The encoder uses 4096 surface points as input;
2. The ratio of volume points to near points (points close to the mesh surface) is 1:1.

Hope this information is helpful to you.
