### ISSUE TITLE
clip-vit-large-patch14 no config.json error

### ISSUE THREAD

**Issue by metanoder** [NeuralCarver/Michelangelo#6]
After installation, running the text2mesh inference, or any inference, and i get this error...

OSError: ./checkpoints/clip/clip-vit-large-patch14 does not appear to have a file named config.json. Checkout 'https://huggingface.co/./checkpoints/clip/clip-vit-large-patch14/None' for available files.

Clicking the link will result in a huggingface 404 and no content stored.  Can you point to where I can find the config.json to clip-vit-large-patch14?  Or how do I debug this?

**Comment by Maikouuu** [comment]
Hi,

Have you downloaded the checkpoint from [My Hugging Face](https://huggingface.co/Maikou/Michelangelo/tree/main/checkpoints)? If not, you can try downloading the checkpoint from there, as I have provided all the necessary files. 

If you encounter any issues while downloading CLIP, you can consider downloading it from [CLIP's Hugging Face page](https://huggingface.co/openai/clip-vit-large-patch14). Once the download is complete, remember to modify line [26](https://github.com/NeuralCarver/Michelangelo/blob/b53fa004cd4aeb0f4eb4d159ecec8489a4450dab/configs/text_cond_diffuser_asl/text-ASLDM-256.yaml#L26C1-L26C76) and line [34](https://github.com/NeuralCarver/Michelangelo/blob/b53fa004cd4aeb0f4eb4d159ecec8489a4450dab/configs/text_cond_diffuser_asl/text-ASLDM-256.yaml#L34).

**Comment by metanoder** [comment]
I tried re-cloning from your hugging face checkpoints repo, but the problem persisted.  After downloading from CLIP's repo and placing it in checkpoint/clip, then the model started running.

Thanks for the response and links.  Your project is quite impressive!  Bravo!

ancillary sidenote, for Windows users, running wsl2 + ubuntu 22.04, will have issues.  As discussed in [issue 786](https://github.com/microsoft/WSL/issues/8587) it is just a matter to add this in the .bashrc:
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

cheers!

**Comment by Maikouuu** [comment]
Thanks for usage and suggestions. I will include it in the TIPS section of the github page and link to this issue.

cheers!
